{% set name = "intake-satpy" %}
{% set version = "0.1.0.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake_satpy-{{ version }}.tar.gz
  sha256: 10d62d93b2f03cfed64f2471748fd529bf1ccf2b44382d2770d33d45b762c3fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - intake
    - intake-xarray
    - satpy

test:
  imports:
    - intake_satpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/intake-satpy/
  summary: Intake drivers using Satpy to read and manipulate data
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - djhoese
